import {
  AlertTriangle,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  CalendarCheck,
  Car,
  ClipboardList,
  CreditCard,
  FileText,
  FolderOpen,
  HandCoins,
  HardDrive,
  History,
  KeyRound,
  LayoutDashboard,
  Megaphone,
  MessageSquare,
  Package,
  Phone,
  PiggyBank,
  Receipt,
  Server,
  Settings,
  Shield,
  ShoppingBag,
  TrendingUp,
  UserCheck,
  UserPlus,
  Users,
  Vote,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  shield: Shield,
  "user-check": UserCheck,
  briefcase: Briefcase,
  package: Package,
  receipt: Receipt,
  "credit-card": CreditCard,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  "hand-coins": HandCoins,
  "bar-chart": BarChart3,
  megaphone: Megaphone,
  "alert-triangle": AlertTriangle,
  "book-open": BookOpen,
  "message-square": MessageSquare,
  "calendar-check": CalendarCheck,
  building: Building2,
  "shopping-bag": ShoppingBag,
  car: Car,
  phone: Phone,
  "file-text": FileText,
  vote: Vote,
  "folder-open": FolderOpen,
  users: Users,
  "user-plus": UserPlus,
  "clipboard-list": ClipboardList,
  wrench: Wrench,
  "hard-drive": HardDrive,
  bell: Bell,
  "key-round": KeyRound,
  history: History,
  settings: Settings,
  server: Server,
};

export function getNavIcon(iconKey: string): LucideIcon {
  return ICON_MAP[iconKey] ?? LayoutDashboard;
}
